
SCRIPT(k)
=========

NAME
----
ctags - a

Options
-------

*ctagsfiles* 'str-list'::
	default 'tags'
....
colon separated list of paths to tag files to parse when looking up a symbol
....

*ctagsopts* 'str'::
	default '-R'
....
options to pass to the `ctags` shell command
....

*ctagspaths* 'str'::
	default '.'
....
path to the directory in which the tags file will be generated
....

Commands
--------

*tag*::
....
tag [<symbol>]: jump to a symbol's definition
If no symbol is passed then the current selection is used as symbol name
....

*tag-complete*::
....
Insert completion candidates for the current selection into the buffer's local variables
....

*ctags-funcinfo*::
....
Display ctags information about a selected function
....

*ctags-enable-autoinfo*::
....
Automatically display ctags information about function
....

*ctags-disable-autoinfo*::
....
Disable automatic ctags information displaying
....

*ctags-generate*::
....
Generate tag file asynchronously
....

*update-tags*::
....
Update tags for the given file
....
